### ISSUE TITLE
Fatser RCNN bottom up features for TDIUC

### ISSUE THREAD

**Issue by ak-kat** [erobic/faster-rcnn.pytorch#1]
Could you please share the code or bottom up features for TDIUC visual question answering dataset.

Thanks in advance.

**Comment by erobic** [comment]
I had used the original UpDn repository: https://github.com/peteanderson80/bottom-up-attention to extract the features. They already provide features for COCO, and I had just extracted features for remaining TDIUC images not in COCO. Unfortunately, I don't have the exact script right now.
