### ISSUE TITLE
how to download the pretrained faster rcnn model for CLVER

### ISSUE THREAD

**Issue by SkyOL5** [erobic/faster-rcnn.pytorch#3]
When I download the pth file, there are only three lines show the "version, oid, size" info for the file. I tried to learn how to use git lfs to download it but failed...

Do you have any recommend website for learning how to do it? Or can you provide us some instructions for download file from git lfs?

Thank you very much! @erobic

**Comment by erobic** [comment]
Thank you for notifying me about this. I updated the link with: https://drive.google.com/file/d/1duANFkDhANB0IV3gFonSKG6BiMLPQoWX/view?usp=sharing
